#!/bin/bash

grep -v ");" /var/www/html/nextcloud/config/config.php > /var/www/html/nextcloud/config/config2.php
echo ");" >> /var/www/html/nextcloud/config/config2.php
mv /var/www/html/nextcloud/config/config2.php /var/www/html/nextcloud/config/config.php

function eof {
  cd;
  rm -rf ~/nextcloud-fix;
  systemctl reboot;
}

trap eof EXIT
